/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlockEvaluation = IDL.Record({
  'blockId' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'totalPossible' : IDL.Nat,
});
export const TriviaSession = IDL.Record({
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addBlockEvaluation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addTriviaSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'getAllBlockEvaluations' : IDL.Func(
      [],
      [IDL.Vec(BlockEvaluation)],
      ['query'],
    ),
  'getAllTriviaSessions' : IDL.Func([], [IDL.Vec(TriviaSession)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlockEvaluation = IDL.Record({
    'blockId' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'totalPossible' : IDL.Nat,
  });
  const TriviaSession = IDL.Record({
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addBlockEvaluation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'addTriviaSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'getAllBlockEvaluations' : IDL.Func(
        [],
        [IDL.Vec(BlockEvaluation)],
        ['query'],
      ),
    'getAllTriviaSessions' : IDL.Func([], [IDL.Vec(TriviaSession)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };